### PR TITLE
[VEN-831] feat: add green pulse active animation

### PR DESCRIPTION
**Pull request by coreyar**
## Jira ticket(s)

VEN-831

## Changes

Adds a green pulse animation for active proposals as part of governance update

### CODE REVIEW

**Review by therealemjy — CHANGES_REQUESTED** [review]
Screen Shot 2022-12-19 at 20 49 33

The animated green pulse looks a bit small. The link Pavel gave me for the Figma design doesn't work anymore, but I remember seeing the dot a bit bigger.

There's also no more spacing between the timestamp and the countdown.

**Comment by coreyar** [comment]
> The animated green pulse looks a bit small. The link Pavel gave me for the Figma design doesn't work anymore, but I remember seeing the dot a bit bigger.
> 
If you scroll to the bottom left of the Votes page in Figma you can see. The link doesn't work for me either not sure what happened

**Comment by therealemjy** [comment]
Looks good. Now we just need to remove the "Active" tag on the top right of the component:
Screen Shot 2022-12-20 at 09 46 19

**Comment by coreyar** [comment]
> Looks good. Now we just need to remove the "Active" tag on the top right of the component: Screen Shot 2022-12-20 at 09 46 19

I was going to do that in another PR where I updated the chips. I went ahead and updated the chips in this branch.

These new chips won't be visible till we update the comptroller. I'm going to put those changes in a different branch

**Comment by therealemjy** [comment]
@coreyar 
Makes sense, thank you

**Comment by coreyar** [comment]
Rebased on to 894

**Pull request closed without merging**
