### PR TITLE
update codebase

### PR DESCRIPTION
**Pull request by kvezo**
- update wallet integration
- update data fetch module
- remove redux store data

### CODE REVIEW

**Comment by RoseRompkxm** [comment]
do we still need `saga` merchanism? seem likes we can delete them @zurab-kvezo

**Comment by kvezo** [comment]
> do we still need `saga` merchanism? seem likes we can delete them @zurab-kvezo

I agree. we can create new issue for this.

**Comment by RoseRompkxm** [comment]
image
seems like latest block is forgetten to be set @zurab-kvezo

**Comment by kvezo** [comment]
> image seems like latest block is forgetten to be set @zurab-kvezo

you are right. i will add it.

**Pull request merged**
